DATA:
  DATASET: "cifar10"
  DIR: "/home/kai/.torch/data"
  BS: 128
  NUM_CLASSES: 10

MODEL:
  MODEL: "resnet34"

OPTIMIZER:
  TYPE: adam
  WEIGHT_DECAY: 0.0001
  LR: 0.1
  GAMMA: 0.1
  MOMENTUM: 0.9
  WARMUP_EPOCHS: 0
  MILE_STONES: [90, 135]

CUDA:
  CUDA: True
  GPU_ID: 0
  DATA_PARALLEL: False

VISDOM:
  VISDOM: True
  PORT: 8097

MISC:
  LOGFREQ: 20
  TMP: "tmp/resnet34-cifar10"

